# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 The Foundry Visionmongers Ltd

# Composite action for reuse within other workflows.
# Builds OpenAssetIO.
# Should be run on a ghcr.io/openassetio/openassetio-build container.

name: Build OpenAssetIO
description: Builds OpenAssetIO and publishes an artifact
runs:
  using: "composite"
  steps:
    - name: Checkout OpenAssetIO
      uses: actions/checkout@v3
      with:
        repository: OpenAssetIO/OpenAssetIO
        path: openassetio-checkout

    - name: Build OpenAssetIO
      shell: bash
      run: |
        cd openassetio-checkout
        mkdir build
        cmake -G Ninja -S . -B build
        cmake --build build
        cmake --install build

    - uses: actions/upload-artifact@v3
      with:
        name: OpenAssetIO Build
        path: openassetio-checkout/build/dist
        retention-days: 1
